import { FormPage } from '../../_components/form-page';
export const metadata = { title: 'Nova carga' };
export default function Page() { return <FormPage eyebrow="Operação • Cargas" title="Nova carga" description="Entrada operacional completa preparada para itens, volumes, requisitos, matching e negociação." backHref="/cargas" groups={[
  {title:'Identificação comercial',description:'Cliente, referência e modalidade da operação.',fields:[{name:'customer',label:'Cliente',required:true},{name:'reference',label:'Referência do cliente'},{name:'mode',label:'Modalidade',options:['Dedicada','Complemento','Compartilhada'],required:true},{name:'costCenter',label:'Centro de custo'}]},
  {title:'Rota',description:'Origem, destino e janelas operacionais.',fields:[{name:'origin',label:'Origem',required:true,wide:true},{name:'pickupDate',label:'Coleta prevista',type:'date'},{name:'destination',label:'Destino',required:true,wide:true},{name:'deliveryDate',label:'Entrega prevista',type:'date'}]},
  {title:'Carga e volumes',description:'Características físicas para compatibilidade.',fields:[{name:'cargoType',label:'Tipo de carga',required:true},{name:'species',label:'Espécie / embalagem'},{name:'weightKg',label:'Peso total (kg)',type:'number',required:true},{name:'volumeM3',label:'Cubagem total (m³)',type:'number'},{name:'volumeCount',label:'Quantidade de volumes',type:'number'}]},
  {title:'Requisitos de transporte',description:'Restrições e recursos necessários.',fields:[{name:'vehicleType',label:'Tipo de veículo',required:true},{name:'bodyType',label:'Carroceria',required:true},{name:'tracking',label:'Exige rastreamento',options:['Sim','Não']},{name:'stackable',label:'Pode empilhar',options:['Sim','Não']},{name:'notes',label:'Observações operacionais',wide:true}]},
  {title:'Valores',description:'Parâmetros comerciais iniciais sem substituir a negociação.',fields:[{name:'targetFreight',label:'Frete alvo (R$)',type:'number'},{name:'toll',label:'Pedágio previsto (R$)',type:'number'},{name:'paymentTerm',label:'Condição de pagamento'}]},
 ]} checklist={['Origem e destino válidos','Peso/cubagem coerentes','Requisitos compatíveis','Referências não duplicadas','Eventos de status auditáveis']} />; }
